apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: env-green-api-ingress
  namespace: env-green
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`env-green.leunamnauj.local`)
    priority: 10
    services:
    - name: env-green
      namespace: env-green
      port: 443
  tls:
    passthrough: true