
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: env-yellow-api-ingress
  namespace: env-yellow
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`env-yellow.leunamnauj.local`)
    priority: 10
    services:
    - name: env-yellow
      namespace: env-yellow
      port: 443
  tls:
    passthrough: true