---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-green-crossplane-providers
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    clusterName: env-green
spec:
  project: default
  sources:
    - path: environments/env-green/crossplane-providers
      repoURL: https://github.com/leunamnauj/Engineering-Multi-Tenancy-for-Crossplane-Automating-Environments-with-vClusters-and-GitOps.git
      targetRevision: HEAD
  
  destination:
    server: https://env-green.env-green:443
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 5
        maxDuration: 3m0s

