---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider-nginx
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: vcluster-kubeconfig
      key: kubeconfig
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: nginx-ns
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: nginx-ns

  providerConfigRef:
    name: kubernetes-provider-nginx
    
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: deployment-nginx
  namespace: nginx-ns
spec:
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx
        namespace: nginx-ns
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:latest
              ports:
              - containerPort: 80

  providerConfigRef:
    name: kubernetes-provider-nginx

---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: service-nginx
  namespace: nginx-ns
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-service
        namespace: nginx-ns
      spec:
        selector:
          app: nginx
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80
        type: ClusterIP

  providerConfigRef:
    name: kubernetes-provider-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ns-ingress
  namespace: nginx-ns
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ingressClassName: traefik
  rules:
    - host: nginx.env-green.leunamnauj.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
